services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: amanclash4321/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: amanclash4321/backend:latest
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
