name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy frontend
        run: |
          kubectl apply -f K8s/frontend-deployment.yaml
          kubectl apply -f K8s/frontend-service.yaml
          kubectl rollout restart deployment frontend

      - name: Deploy backend
        run: |
          kubectl apply -f K8s/backend-deployment.yaml
          kubectl apply -f K8s/backend-service.yaml
          kubectl rollout restart deployment backend

      - name: Apply Ingress
        run: kubectl apply -f K8s/ingress.yaml

      - name: Apply Horizontal Pod Autoscaler
        run: kubectl apply -f K8s/hpa.yaml

      - name: Apply Let's Encrypt ClusterIssuer
        run: kubectl apply -f K8s/lets-encrypt.yaml
